openapi: 3.0.2
info:
  title: 'Huwelijks Planner'
  version: V.0.1
  description: |
    API Details
    - Component: Huwelijks Planner
    - Reference: hpui
    - Enviroment: dev
    - Version: V.0.1
    - Repository: [online](https://github.com/ConductionNL/huwelijksplanner-ui) / [zip](https://github.com/ConductionNL/huwelijksplanner-ui/archive/master.zip)
    - Docker Image: [online]() 
    - Datamodel: [postman](/schema/hpui.postman_collection.json) / [oas](/schema/openapi.yaml) / [pdf](/schema/datamodel.pdf) / [mwb](/schema/datamodel.mwb) 
    
    'Dit is de huwelijksplanner app'         
    
paths:
  '/adresses/{id}/audit_trail':
    get:
      tags:
        - CacheItem
      operationId: get_audit_trailCacheItemItem
      summary: 'Retrieves a CacheItem resource.'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: string
        -
          name: Authorization
          description: 'The JWT of the entity performing the request'
          in: header
        -
          name: API-Version
          description: 'The version of the API conform [Landelijke API-strategie.](https://geonovum.github.io/KP-APIs/#versioning)'
          example: 1.0.1
          in: header
        -
          name: X-NLX-Logrecord-ID
          description: 'A  globally unique id of the request, which makes a request traceable throughout the network.'
          in: header
        -
          name: X-NLX-Request-Process-Id
          description: 'A process id for purpose registration (doelbinding)'
          in: header
        -
          name: X-NLX-Request-Data-Elements
          description: 'A list of requested data elements'
          in: header
        -
          name: X-NLX-Request-Data-Subject
          description: 'A key-value list of data subjects related to this request. e.g. `bsn=12345678, kenteken=ab-12-fg`'
          in: header
        -
          name: X-NLX-Audit-Clarification
          description: 'A clarification as to why a request has been made  (doelbinding)'
          in: header
        -
          name: Link
          description: 'A [websub](https://www.w3.org/TR/websub/#discovery) header like <https://hub.example.com/>; rel="hub"'
          in: header
        -
          name: 'extend[]'
          required: false
          description: 'An array of nested objects to include in the return object'
          in: query
          schema:
            type: array
        -
          name: 'fields[]'
          required: false
          description: 'An array of fields to return in output, wil return all fields is not supplied'
          in: query
          schema:
            type: array
        -
          name: validOn
          required: false
          description: 'Returns object as valid on a given date time'
          schema:
            type: string
            format: date-time
          in: query
        -
          name: validFrom
          required: false
          description: 'Returns objects valid from a given date time'
          schema:
            type: string
            format: date-time
          in: query
        -
          name: validUntil
          required: false
          description: 'Returns objects valid until a given date time'
          schema:
            type: string
            format: date-time
          in: query
      responses:
        200:
          description: 'CacheItem resource response'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/CacheItem:jsonld-read'
            application/json+ld:
              schema:
                $ref: '#/components/schemas/CacheItem:jsonld-read'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/json+hal:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/json+vnd.api:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/json:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/health+json:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/json+health:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/xml:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            text/csv:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            text/html:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
        404:
          description: 'Resource not found'
      produces:
        - application/health+json
  '/adresses/{id}/change_log':
    get:
      tags:
        - CacheItem
      operationId: get_change_logsCacheItemItem
      summary: 'Retrieves a CacheItem resource.'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: string
        -
          name: Authorization
          description: 'The JWT of the entity performing the request'
          in: header
        -
          name: API-Version
          description: 'The version of the API conform [Landelijke API-strategie.](https://geonovum.github.io/KP-APIs/#versioning)'
          example: 1.0.1
          in: header
        -
          name: X-NLX-Logrecord-ID
          description: 'A  globally unique id of the request, which makes a request traceable throughout the network.'
          in: header
        -
          name: X-NLX-Request-Process-Id
          description: 'A process id for purpose registration (doelbinding)'
          in: header
        -
          name: X-NLX-Request-Data-Elements
          description: 'A list of requested data elements'
          in: header
        -
          name: X-NLX-Request-Data-Subject
          description: 'A key-value list of data subjects related to this request. e.g. `bsn=12345678, kenteken=ab-12-fg`'
          in: header
        -
          name: X-NLX-Audit-Clarification
          description: 'A clarification as to why a request has been made  (doelbinding)'
          in: header
        -
          name: Link
          description: 'A [websub](https://www.w3.org/TR/websub/#discovery) header like <https://hub.example.com/>; rel="hub"'
          in: header
        -
          name: 'extend[]'
          required: false
          description: 'An array of nested objects to include in the return object'
          in: query
          schema:
            type: array
        -
          name: 'fields[]'
          required: false
          description: 'An array of fields to return in output, wil return all fields is not supplied'
          in: query
          schema:
            type: array
        -
          name: validOn
          required: false
          description: 'Returns object as valid on a given date time'
          schema:
            type: string
            format: date-time
          in: query
        -
          name: validFrom
          required: false
          description: 'Returns objects valid from a given date time'
          schema:
            type: string
            format: date-time
          in: query
        -
          name: validUntil
          required: false
          description: 'Returns objects valid until a given date time'
          schema:
            type: string
            format: date-time
          in: query
      responses:
        200:
          description: 'CacheItem resource response'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/CacheItem:jsonld-read'
            application/json+ld:
              schema:
                $ref: '#/components/schemas/CacheItem:jsonld-read'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/json+hal:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/json+vnd.api:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/json:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/health+json:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/json+health:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/xml:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            text/csv:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            text/html:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
        404:
          description: 'Resource not found'
      produces:
        - application/health+json
  /cache_items:
    post:
      tags:
        - CacheItem
      operationId: postCacheItemCollection
      summary: 'Creates a CacheItem resource.'
      responses:
        201:
          description: 'CacheItem resource created'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/CacheItem:jsonld-read'
            application/json+ld:
              schema:
                $ref: '#/components/schemas/CacheItem:jsonld-read'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/json+hal:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/json+vnd.api:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/json:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/health+json:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/json+health:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/xml:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            text/csv:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
            text/html:
              schema:
                $ref: '#/components/schemas/CacheItem-read'
        400:
          description: 'Invalid input'
        404:
          description: 'Resource not found'
      requestBody:
        content:
          application/ld+json:
            schema:
              $ref: '#/components/schemas/CacheItem:jsonld-write'
          application/json+ld:
            schema:
              $ref: '#/components/schemas/CacheItem:jsonld-write'
          application/hal+json:
            schema:
              $ref: '#/components/schemas/CacheItem-write'
          application/json+hal:
            schema:
              $ref: '#/components/schemas/CacheItem-write'
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CacheItem-write'
          application/json+vnd.api:
            schema:
              $ref: '#/components/schemas/CacheItem-write'
          application/json:
            schema:
              $ref: '#/components/schemas/CacheItem-write'
          application/health+json:
            schema:
              $ref: '#/components/schemas/CacheItem-write'
          application/json+health:
            schema:
              $ref: '#/components/schemas/CacheItem-write'
          application/xml:
            schema:
              $ref: '#/components/schemas/CacheItem-write'
          application/x-yaml:
            schema:
              $ref: '#/components/schemas/CacheItem-write'
          text/csv:
            schema:
              $ref: '#/components/schemas/CacheItem-write'
          text/html:
            schema:
              $ref: '#/components/schemas/CacheItem-write'
        description: 'The new CacheItem resource'
      parameters:
        -
          name: Authorization
          description: 'The JWT of the entity performing the request'
          in: header
        -
          name: API-Version
          description: 'The version of the API conform [Landelijke API-strategie.](https://geonovum.github.io/KP-APIs/#versioning)'
          example: 1.0.1
          in: header
        -
          name: X-NLX-Logrecord-ID
          description: 'A  globally unique id of the request, which makes a request traceable throughout the network.'
          in: header
        -
          name: X-NLX-Request-Process-Id
          description: 'A process id for purpose registration (doelbinding)'
          in: header
        -
          name: X-NLX-Request-Data-Elements
          description: 'A list of requested data elements'
          in: header
        -
          name: X-NLX-Request-Data-Subject
          description: 'A key-value list of data subjects related to this request. e.g. `bsn=12345678, kenteken=ab-12-fg`'
          in: header
        -
          name: X-NLX-Audit-Clarification
          description: 'A clarification as to why a request has been made  (doelbinding)'
          in: header
components:
  schemas:
    CacheItem-read:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          description: 'The UUID identifier of this resource'
          externalDocs:
            url: 'http://schema.org/identifier'
          type: string
          format: uuid
        href:
          type: string
          nullable: true
    CacheItem-write:
      type: object
      description: ''
      properties:
        href:
          type: string
          nullable: true
    'CacheItem:jsonld-read':
      type: object
      description: ''
      properties:
        '@context':
          readOnly: true
          type: string
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        id:
          readOnly: true
          description: 'The UUID identifier of this resource'
          externalDocs:
            url: 'http://schema.org/identifier'
          type: string
          format: uuid
        href:
          type: string
          nullable: true
    'CacheItem:jsonld-write':
      type: object
      description: ''
      properties:
        '@context':
          readOnly: true
          type: string
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        href:
          type: string
          nullable: true
definitions:
  CacheItem-read:
    properties:
      id:
        description: 'The UUID identifier of this resource'
        type: string
        example: e2984465-190a-4562-829e-a8cca81aa35d
        format: uuid
      href: []
    required: []
  CacheItem-write:
    properties:
      href: []
    required: []
tags:
  -
    name: CacheItem
    description: |
      
      
      
securityDefinitions:
  JWT-Oauth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/api/oauth/dialog'
    flow: implicit
    scopes:
      read: 'read right to the CacheItem resource'
      write: 'write right to the CacheItem resource'
  JWT-Token:
    type: apiKey
    in: header
    name: Authorization
    scopes:
      read: 'read right to the CacheItem resource'
      write: 'write right to the CacheItem resource'
host: irc.zaakonline.nl
servers:
  -
    name: huwelijksplanner.online
    url: hpui.dev.huwelijksplanner.online
externalDocs:
  -
    description: 'OAS Documentatie'
    url: 'http://proto.demo.common-ground.dev'
x-commonground:
  type: service
  developers:
    -
      name: Conduction
      url: 'https://github.com/ConductionNL'
      email: info@conduction.nl
    -
      name: 'Gemeente ''s-Hertogenbosch'
      url: 'https://github.com/gemeenteshertogenbosch'
      email: info@s-hertogenbosch.nl/
    -
      name: 'Gemeente Utrecht'
      url: 'https://github.com/GemeenteUtrecht'
      email: info@utrecht.nl
  builds:
    -
      name: travis
      logo: 'https://travis-ci.org/api-platform/core.svg?branch=master'
      url: 'https://travis-ci.org/api-platform/core'
    -
      name: appveyor
      logo: 'https://ci.appveyor.com/api/projects/status/grwuyprts3wdqx5l?svg=true'
      url: 'https://ci.appveyor.com/project/dunglas/dunglasapibundle'
    -
      name: codecov
      logo: 'https://codecov.io/gh/api-platform/core/branch/master/graph/badge.svg'
      url: 'https://codecov.io/gh/api-platform/core'
    -
      name: SensioLabsInsight
      logo: 'https://insight.sensiolabs.com/projects/92d78899-946c-4282-89a3-ac92344f9a93/mini.png'
      url: 'https://insight.sensiolabs.com/projects/92d78899-946c-4282-89a3-ac92344f9a93'
    -
      name: 'Scrutinizer Code Quality'
      logo: 'https://scrutinizer-ci.com/g/api-platform/core/badges/quality-score.png?b=master'
      url: 'https://scrutinizer-ci.com/g/api-platform/core/?branch=master'
