apiVersion: v1
appVersion: V.0.1
description: 'Dit is de huwelijksplanner app'
name: hpui
version: 0.1.0
home: pc.zaakonline.nl
icon: pc.zaakonline.nl
dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
      condition: postgresql.enabled
