apiVersion: v1
entries:
  hpui:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-10T17:12:37.3315623Z"
    description: '&#039;Dit is de huwelijksplanner app&#039;'
    digest: ccc5f897241140bcdce6c30b15536fce48584829efc3a41e7176358109f921d3
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: hpui
    urls:
    - hpui-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-10T17:12:37.3272862Z"
