#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_api_cachedelete:
    path: /api/cache_items
    methods: ['POST']
    defaults:
        _controller: App\Controller\ApiController::cacheDeleteAction
        _api_resource_class: App\Entity\CacheItem
        _api_collection_operation_name: post
